### ISSUE TITLE
DynatraceTextFormatter timestamp and hostname not well formed

### ISSUE THREAD

**Issue by pfelixz** [iojancode/Serilog.Sinks.Dynatrace#8]
When using this Sink with ingestUrl pointing to local agent "http://127.0.0.1:14499/v2/logs/ingest" the date formated is not supported, OneAgent returns an error with a date time out of range. 

Instead of using logEvent.Timestamp.ToString("o") use logEvent.Timestamp.ToUniversalTime().ToString("yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fff'Z'"). 

Hostname is not a fully qualified domain name instead of using only Dns.GetHostName() use Dns.GetHostName() and IPGlobalProperties.GetIPGlobalProperties().DomainName.

entity.process_group_instance is not bind to the log entry, so the log will not be shown in log tab of the trace, probably is not an issue of this Sink, but rather of Dynatrace property Enrichment process.

**Comment by iojancode** [comment]
Hello, thanks, working on this bug.

Regarding hostname with FQDN is not supported, but you could use extensión like this: 
```
var log = new LoggerConfiguration()
    .WriteTo.Dynatrace(
        accessToken: "xxx.yyyyyy.zzzzz",
        ingestUrl: "https://{your-environment-id}.live.dynatrace.com/api/v2/logs/ingest",
        hostName: $"{Dns.GetHostName()}.{IPGlobalProperties.GetIPGlobalProperties().DomainName}")
    .CreateLogger();
```

Regarding entity.process_group_instance, please point me to relevant documentation to check.

**Comment by iojancode** [comment]
Hi, I just release 1.0.6 version of the Nuget at https://www.nuget.org/packages/Serilog.Sinks.Dynatrace/1.0.6 . Could you please give it a try and feedback ?

**Comment by pfelixz** [comment]
Hello, 

sorry for my absence.

> Regarding hostname with FQDN is not supported, but you could use extensión like this:
> var log = new LoggerConfiguration()
>     .WriteTo.Dynatrace(
>         accessToken: "xxx.yyyyyy.zzzzz",
>         ingestUrl: "https://{your-environment-id}.live.dynatrace.com/api/v2/logs/ingest",
>         hostName: $"{Dns.GetHostName()}.{IPGlobalProperties.GetIPGlobalProperties().DomainName}")
>     .CreateLogger();
> 
> Regarding entity.process_group_instance, please point me to relevant documentation to check.

unfortunately we can't use like this, because we are using json LoggerConfiguration. if you could provide us a solution thru json configuration, your help will be very appreciated.

> Regarding entity.process_group_instance, please point me to relevant documentation to check.

DynaTrace assumed it was a bug, only works in file logging channel, the log enrichment process does not add   entity.process_group_instance on other logging channels (event viewer, api, etc) and with out it the logs are not show in traces.

Please see https://www.dynatrace.com/support/help/observe-and-explore/logs/log-monitoring/log-monitoring-configuration/log-enrichment#tabgroup--log-enrichment--globally

**Comment by iojancode** [comment]
Hi, after reading documentation for `entity.process_group_instance`, I believe this is a enrichment exclusive from OneAgent and should not be included on this sink.

> 
> > Regarding entity.process_group_instance, please point me to relevant documentation to check.
> 
> DynaTrace assumed it was a bug, only works in file logging channel, the log enrichment process does not add entity.process_group_instance on other logging channels (event viewer, api, etc) and with out it the logs are not show in traces.
> 
> Please see https://www.dynatrace.com/support/help/observe-and-explore/logs/log-monitoring/log-monitoring-configuration/log-enrichment#tabgroup--log-enrichment--globally

**Comment by iojancode** [comment]
I could not be done through configuration, sorry.

> unfortunately we can't use like this, because we are using json LoggerConfiguration. if you could provide us a solution thru json configuration, your help will be very appreciated.
